[package]
name = "systemd-tmpfile"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
clap = { version = "4", features = ["derive", "env"] }
env_logger = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
file-mode = "0.1"

[profile.release]
debug = true
